menu:
  home: /
  archives: archives
  tags: tags
  about: about
  search: search

title: fredaBoonsong

profile: 
  #logo: Nayo
  author: fredaBoonsong
  avatar: /images/profile.jpg  
  description: fredaBoonsong

favicon: favicon.ico

# social link
social:  
  Github: https://github.com/fredaBoonsong
  # Weibo:
# Zhihu:
  # Facebook:
  # Twitter:
  # Instagram:
  # LinkedIn:


# toc
# 文章的目录 仅识别 H1 和 H2/H3
toc:
    false

# site analytics 
# 站点访问统计
# [ analytics id ]
baidu_analytics:
# 636802045446222199ae541e32c8133e 
google_analytics: 

# comment

# disqus(https://disqus.com/)
disqus:
  comment: true
  shortname: fredaboonsong

# valine(https://github.com/xCss/Valine)
# 创建 leancloud 应用 获取 id|key 填入即可
leancloud:  
  comment: false
  app_id: cFM0eCo0CQ9xmBXmHi1eltol-gzGzoHsz
  app_key: oh9tizsnvV2vNvWgqEvoNtQO

# mob share(http://www.mob.com)
# 文章分享功能
mob_share:
  true

share_item:
- qq
- weixin
- weibo
- douban
- facebook
- twitter
#- tumblr
- google


# donate
# 捐赠功能
# source/imgaes/
donate:
  enable: true
  word: 世界美好 你也是
  wechat: /images/donate1.png
  alipay: /images/donate2.png

# mathjax 
# 渲染LateX公式
# 在post文章头部添加:
#   mathjax: true
# 即可在当前post开启mathjax
mathjax:
  enable: true
  
# excerpt_ignore [boolean]
# increase at the top of your article
# Does this article need to hide the excerpt ?


footer:
  author: fredaBoonsong
  since: 2018

version:
  0.2.2